### ISSUE TITLE
Quick start guide doesn't mention Vercel deployment

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1015]
On our [quickstart guide](https://tina.io/guides/tina-cloud/starter/create-account/), we instruct the user to use localhost as a site URL. This is usually correct when getting started, however, we are guiding them to the flow that now includes the Vercel deployment
Maybe we should gear [this second page](https://tina.io/guides/tina-cloud/starter/create-account/) towards the Vercel deployment, and instruct the user to add localhost:3000 within the 3rd [Getting up and running locally](https://tina.io/guides/tina-cloud/starter/local/) page.

**Comment by jamespohalloran** [comment]
We've also added an experiment where we give the user the option to run the site locally. This may be worth putting in the guide too. 
Because both of these options setup the "Site URL"s for the user, we can probably simplify/remove this section of the guide: https://tina.io/guides/tina-cloud/starter/create-account/#site-urls

<img width="697" alt="Screen Shot 2021-08-31 at 3 00 06 PM" src="https://user-images.githubusercontent.com/3323181/131652428-34b24572-07f8-4b09-830a-f7d200573da7.png">
<img width="986" alt="Screen Shot 2021-09-01 at 7 01 05 AM" src="https://user-images.githubusercontent.com/3323181/131652438-b6c53b41-d910-4b08-9ff7-d651ddf27aa8.png">

**Comment by DirtyF** [comment]
Related: adding a path to start locally directly from https://tina.io/docs/ would be useful.

**Comment by perkinsjr** [comment]
This can now be closed as we have removed the guide in favor of our slick new App flow.
