### ISSUE TITLE
Documentation from Dogfooding Exercise

### ISSUE THREAD

**Issue by Enigmatical** [tinacms/tinacms.org#1029]
The main purpose of the document is something I encountered while dogfooding.  

I noticed that we're lacking examples of how to handle a more complex schema where you might be using a simple `object` and a polymorphic `object` with `templates`.

Luckily, I knew that we use a similar `schema` in the `tina-cloud-starter` and was able to unblock myself, but felt that we should have something in the documentation that goes over the process of writing the `schema`, writing the `query`, and writing the `render` - and how all of those parts fit together.

So far, I have a really rough draft attached to this issue (mostly just a paired down code example with some high level descriptions).

I think it could go with https://tina.io/docs/schema/ or https://tina.io/docs/graphql/ , but I'm honestly not sure.

[advanced-schema.md](https://github.com/tinacms/tinacms.org/files/7101767/advanced-schema.md)

**Comment by Enigmatical** [comment]
I've reached out to @perkinsjr for some insight into finding the "voice" for this and where to target it.  I'm also open to any other opinions as I've not really wrote _documentation_ before (for a wider audience).

**Comment by perkinsjr** [comment]
I modified this and now have a PR great work @Enigmatical, I made small voice and tone and formatting changes and the rest looks and feels great!
