### ISSUE TITLE
Simplify "content modelling" intro doc

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1067]
https://tina.io/docs/schema/

Potential improvements:
- [x] ["Collections"](https://tina.io/docs/schema/#collections) appears on the same level as ["fields"](https://tina.io/docs/schema/#fields)
- [x] Fields could be broken out into a reference doc
- [x] We use "fields" in two contexts here:  higher level "fields" vs the `ui: { component }` "fields". ("Field Plugins" in the legacy/toolkit docs are sometimes just refered to as fields).
- [x] We don't document "label", "name", or "path"
- [ ] Should we have some links to show how to work with content modelling after writing in the schema.ts file? (E.g, browsing altair, using the CLI to update types/client, etc)
- [x] We link to the legacy field docs
- [x] Some of the fields work with the "list" property, and some don't (It's unclear which)
- [ ] Unclear why some fields like "image" gets it's own scalar type (when it's just text), vs a field like "color"
- [ ] Is "scalar" vs "nonscalar" an accurate way of distinguishing between these fields?

**Comment by jeffsee55** [comment]
We've wanted to bring those same types into the component UI, so `object` and `reference` would be a first-class API in `@tinacms/toolkit`. This was part of what we'd hope to achieve in the UI cohesion work this quarter but we may not get to it at this point as we've shifted resources. But in general, I agree this is a potential stumbling point and I think that would be easier to explain if the "toolkit" docs were treated as their own entity

**Comment by jeffsee55** [comment]
Also, I definitely think we should fix the areas where we're calling toolkit docs "legacy"

**Comment by jamespohalloran** [comment]
Perhaps some more improvements we can make with some user feedback, but I think for the scope of this ticket can be considered complete
