### ISSUE TITLE
Improve Introduction/overview doc

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1071]
https://tina.io/docs/

Our main intro doc feels a bit dated in how it frame's Tina.

- [x] The vibe is that the toolkit & the JS toolkit are different products, which goes against the new higher level direction of the docs
- [x] Should the quickstart be linking to the guides instead of the next Intro doc. 
- [x] Should this maybe provide an optional link to the UI quickstart for less technical users?

**Comment by ashleyjanedoiron** [comment]
PR: https://github.com/tinacms/tinacms.org/pull/1174
