### ISSUE TITLE
Guides: Are they useful, and up to date?

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1073]
Our guides are a main CTA on the tina.io homepage, and on the [docs index](https://tina.io/docs/).

We have two guides: 
- Using the starter
- Adding Tinacms to an existing repository

We've made it easier to get started with the starter (Now you can use the quickstart). Is this path easier to get started, than the "Basic features" concept docs? 
Maybe we keep the guides, but make them only accessible through the sidebar, instead of such high-traffic'ed CTA's?

**Comment by perkinsjr** [comment]
The guides should stay and the CTA's should go away, we should always have guides. Not everyone finds Tina from our homepage or wants to just jump in with no context. We should also go through them again and update them to the latest TIna (at least the adding to the existing site).
