### ISSUE TITLE
improve CLI reference docs

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1074]
We currently have two CLI reference docs.
https://tina.io/docs/cli-overview/
https://tina.io/docs/cli/

- [ ] They both kind of read for like a guide, than reference material
- [ ] Do we need two separate docs? If so, can we group them better?

**Comment by jamespohalloran** [comment]
Touched on this with this PR: https://github.com/tinacms/tinacms.org/pull/1109

**Comment by perkinsjr** [comment]
Touched on another PR #1112
