### ISSUE TITLE
"Field Component" reference docs improvements

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1118]
Our field component reference docs haven't changed since pulling them up from the toolkit.  A few potential improvements I can envision:

- [ ] They don't reference how to use when within a schema. E.g, a color field component would need to be created using the "text" schema type, and a UI "color" component. 
Note: If some one is looking for a select field, they will probably search "select", and it will lead them to the field plugin instead of the content modelling doc. It can be hard to know how it's actually used.
- [ ] Likely references to outdated form usage, e.g: https://tina.io/docs/reference/toolkit/fields/group/#definition
- [ ] Do certain fields still need to be imported from separate packages?

**Comment by jamespohalloran** [comment]
Just to bring this one to the surface, as I was going through the [htmlproofer PR](https://github.com/tinacms/tinacms.org/pull/1168) to fix our broken links, there was a lot of references to docs/packages that are no longer supported, Gatsby support, etc. 

I think it will be important that if someone lands on a doc like: https://tina.io/docs/reference/toolkit/fields/group-list/, we don't steer them down an outdated path where they need to comb through outdated packages.

**Comment by jamespohalloran** [comment]
I think a site-wide banner on our beta docs is a good idea: https://pre-beta.tina.io

Anything in our actual docs should ideally still be relevant though. The reason we kept the field plugin docs was because you'd need to know how to extend it, and which props you'd need to implement to customize it. E.g 

E.g: With the radio field, you could theoretically implement the `variant` option, which isn't documented elsewhere https://tina.io/docs/reference/toolkit/fields/radio-group/. There are lots of potential tripping points to tease out the relevant info though.

**Comment by jeffsee55** [comment]
We'd intended to make these low-level fields reflect the "primitives" more closely, but haven't gotten to it. Last we chatted about it, something like this:

Core Field Plugins
- TextFieldPlugin -> StringFieldPlugin
  - Tip: Customize with ColorFieldPlugin
- NumberFieldPlugin
- DateFieldPlugin
- ImageFieldPlugin
- ToggleFieldPlugin -> BooleanFieldPlugin
Add
- ObjectFieldPlugin
  - Demonstrate using with `fields` property
  - Demonstrate using with `templates` property
- Rich text
  - Add the ability for this component to parse/stringify markdown client-side.
Introduce "modifiers" concept:
- Any of these can take `list: true`
  - Tip: Customize with TagsFieldPlugin
- Any of these can take an 'options' array:
  - For `list: true`, this will be a CheckboxFieldPlugin by default
  - For `list: false`, this is a SelectFieldPlugin by default
Remove these - or at least describe them as higher-level field plugins and de-emphasize them
- ListFieldPlugin
- GroupFieldPlugin
- GroupListFieldPlugin
- BlocksPlugin
- Markdown
