### ISSUE TITLE
Mobile issues on pages with Graphiql

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1131]
Things look weird on https://tina.io/docs/graphql/queries/ on mobile

<img width="455" alt="Screen Shot 2021-12-03 at 4 25 12 PM" src="https://user-images.githubusercontent.com/3323181/144668303-76bec71c-d399-4b7a-a6eb-4a0f0fa16723.png">

**Comment by perkinsjr** [comment]
This again is an issue and something we should address ASAP, navigating the docs on mobile is almost impossible to read when there is a graphQL example. 

https://tina.io/docs/editing/blocks/#adding-a-visual-block-selector-experimental
