### ISSUE TITLE
Add documentation around noWatch CLI option

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1133]
When I went to deploy to Vercel, I get a bunch of these type of errors:
```(node:860) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/vercel/path0/node_modules/date-fns/esm/_lib/getUTCWeekYear'
(For different dependencies), and the the build hangs indefinitely. I believe this occurred after updating the build command to. be: "yarn tinacms server:start -c \"next build\"" .
``` 

The issue was that my Vercel project was old, so it didn't have the CI environment variable set automatically. 

We should:
- [ ] provide a FAQ for this error
- [ ] Document option in server:start CLI reference 
- [ ] Consider setting --noWatch by default for the build command in our CLI init.

**Comment by jamespohalloran** [comment]
still relevant

**Comment by logan-anderson** [comment]
still relevant

**Comment by logan-anderson** [comment]
@jamespohalloran Do you happen to have the error message(s) that displayed when this happened?

**Comment by jamespohalloran** [comment]
If we're changed the promoted path so that we don't use the filesystem in CI, I'd say this could be tagged wontfix and closed. I don't think I've run into it myself in the last 6 months

**Comment by logan-anderson** [comment]
We also, look at process.env.CI which is true for all new vercel sites

**Comment by jamespohalloran** [comment]
> We also, look at process.env.CI which is true for all new vercel sites

Right, this initially occurred when adding Tina to an old project. I'll close for now, we can revisit if it resurfaces
