### ISSUE TITLE
Add context around queries to our "Editing with blocks" docs

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms.org#1171]
Currently our Blocks editing section has half the information. Based upon what is provided you have no idea what the query should be. This leads users down a bad path. We should provide the query, otherwise the code snippets provided make no sense. Based on the code the query could look like this:

```
getPageDocument(relativePath: "path.md"){
        data{
          blocks{
            __typename
          }
        }
        }
}
}
```

However you need a fragment for each block. which isn't easily found because our example application that this is pulled from uses the client sdk.

Personally, I spent 30-40 minutes figuring out that I needed fragments for each block to make it work correctly.

-- TODO:

- [ ] Add missing query documentation
- [ ] Add a playground example

**Comment by jeffsee55** [comment]
Referring to [this section](https://tina.io/docs/editing/blocks/), we have a "define" section and a "rendering" section, but looks like we need to provide a "querying" section between the two.
