### ISSUE TITLE
Document rendering markdown

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1173]
Our [MDX docs](https://tina.io/docs/editing/mdx/) show an example of rendering out the rich text within a page.

Our [Markdown docs](https://tina.io/docs/editing/markdown/) should do something similar (likely using react-markdown)

**Comment by jeffsee55** [comment]
The gist here is that for our rich-text field we're actually doing the parsing/stringifying on the backend, and that's something we'd like to keep intact. Parsing/stringifying markdown client-side is something we can encourage users _not_ to do, but it'd be nice to support regardless. 

So providing a basic version of stringify/parse that's browser-friendly and deprecating the prosemirror editor would be ideal.

- Short term we'd like to clear up confusion on the docs. For _not_ using `rich-text`, you should use `type: string`, with `ui.component: 'markdown'`. You'll then be responsible for rendering it with something like react-markdown
- Longer term, we'd like to provide `parse/stringify` to the rich-text editor so it's on feature parity with what you can do with a plain markdown string.
  - Investigate getting remark (without mdx) to parse/stringify in the browser.
