### ISSUE TITLE
Remove legacy Tina implementation from tina.io

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1178]
Right now we have a dated pre-TinaCloud version of Tina on tina.io. It uses unsupported features like open-authoring, inline-editing, frontend github-backend, etc.

It will be easier to add the current version of Tina once we remove this dated implementation.

- [x] Remove Tina packages and code
- [x] https://github.com/tinacms/tinacms.org/pull/1210
- [x] #1211
- [x] #1212
- [x] #1213
- [x] #1216
- [x] #1214
- [x] #1215

**Comment by gitsstewart** [comment]
We'll time box this effort to 2 days. If it gets too hairy we can take a step back and re-visit how to do this.

**Comment by gitsstewart** [comment]
First person to work on this needs to document the approach here so that there is consistency. Also create a punchiest here.

**Comment by logan-anderson** [comment]
> First person to work on this needs to document the approach here so that there is consistency. Also create a punchlist here.

@spbyrne removed tina from the community page in https://github.com/tinacms/tinacms.org/pull/1210. We can follow this approach for consistency.

**Comment by spbyrne** [comment]
I'm going to take on the homepage. I recall using a blocks renderer that I can dig up or recreate so it shouldn't be too hard.

**Comment by spbyrne** [comment]
I'm mainly stripping out inline components by taking something like `<InlineTextarea name="subline" />` and replacing it with `{data.subline}`, plus removing the Tina form. The specifics will depend on the page, though.

**Comment by logan-anderson** [comment]
👍  I am going to tackle the docs page. I also removed the gihhub data fetching in `getDocsProps`
