### ISSUE TITLE
SEO: Remove dated & unlinked pages from repo

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1179]
We seem to still have several pieces of content that live in the repo, that isn't linked to from the nav or in the content. 

<img width="580" alt="Screen Shot 2022-01-20 at 11 38 47 AM" src="https://user-images.githubusercontent.com/3323181/150371227-110433e4-26e2-44e4-91c4-321fa251b840.png">

This content still shows up in the search: https://tina.io/docs/tina-init-tutorial/

We should do an audit and:
- [ ] Remove these content files.
- [ ] Add necessary redirects to https://tina.io/docs/legacy-redirect/ or other relevant pages

**Comment by ashleyjanedoiron** [comment]
Closed with : https://github.com/tinacms/tinacms.org/pull/1193
