### ISSUE TITLE
Document visual block selector

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms.org#1234]
The new visual selector is opt-in from the schema. It's now merged but not released; I'm creating this issue to track creating docs, but it's okay to release it before docs are ready (those that are interested can [reference the PR](https://github.com/tinacms/tinacms/pull/2563) to find implementation details for now). 

Potential places to update:
- [Blocks Field](https://tina.io/docs/reference/toolkit/fields/blocks/)
- [The 'object' field](https://tina.io/docs/reference/types/object/)

Things to add:
- API details & options
- An example of the visual selector 

Notes:
Good reference material https://tina.io/docs/editing/blocks/

**Comment by logan-anderson** [comment]
PR here: https://github.com/tinacms/tinacms.org/pull/1252
