### ISSUE TITLE
Tina.io editing issues.

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms.org#1274]
I just created my first post using the editor here are some friction points:

1. When creating a new branch and a new post, it becomes uneditable because contextual editing cannot seem to locate the post. Even though it shows in Admin.  We need to update route mapping. 
3. Ordered and Unordered List editing seems to be broke in the MDX editor and it doesn't actually show the list when editing.

**Comment by spbyrne** [comment]
I've tested and replicated #1 but I don't think it's a route mapping issue. 

- The file is successfully created; it appears in git.
- Tina knows I'm on my new branch; if I open the branch switcher, my new branch is selected.
- The post shows up on the post list page.

**Comment by spbyrne** [comment]
2 is a styling issue with Tina; working on a fix now.

**Comment by perkinsjr** [comment]
> I've tested and replicated 1 but I don't think it's a route mapping issue.
> 
> * The file is successfully created; it appears in git.
> * Tina knows I'm on my new branch; if I open the branch switcher, my new branch is selected.
> * The post shows up on the post list page.

If you then open the file with contextual editing what happens? I assume this would be route mapping not sending you to contextual editing? The admin screen seems to show the file but selecting it doesn't seem to work as expected.

**Comment by spbyrne** [comment]
If I open the page I get a 404 but it's sending me to the correct URL.

**Comment by perkinsjr** [comment]
Hmm, that doesn't feel like the right UX... If I can create it in admin I'd expect the page to open to the file. I think that is a case for read only tokens more then admin / contextual issues

**Comment by spbyrne** [comment]
[Also here's a PR to update the Tina packages so we can troubleshoot this branching issue in style](https://github.com/tinacms/tinacms.org/pull/1278)
