### ISSUE TITLE
Setup Tina.io Data Layer

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms.org#1276]
Performance of TinaCMS on this site feels slow without the data layer.  Also, other people may use our implementation of Tina as a reference example and we want them to have a snappy experience using the data layer

Note: Timebox to a day and if we can't get over the hurdle, create a spike to investigate how to fix it.

**Comment by kldavis4** [comment]
just a note on this.. spent a bit of time attempting to enable the data layer and ran into issues running `yarn build` and `yarn dev-next`. Without increasing the memory available, these die with an out of memory error. Increasing the memory prevents the OOM error, but the process doesn't seem to be completing properly. TLDR this will require some further investigation.

**Comment by logan-anderson** [comment]
> further

I did not run into this error. Did we do anything to fix it?

**Comment by kldavis4** [comment]
@logan-anderson not that I am aware of but it has been a while since I attempted this, so perhaps there was a bug that has been fixed

**Comment by logan-anderson** [comment]
PR: https://github.com/tinacms/tinacms.org/pull/1361
