### ISSUE TITLE
Clicking "fullscreen" on a playground example causes it to crash

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1311]
https://www.loom.com/share/2b7e65dd0622426792c31f9f0761be70

Click the fullscreen icon in a playground causes the embedded playground to go blank

Notes:
* Making it configurable might be good if we can do it
* Need to hide the hamburger menu 
* May need to add a spinner indicator for while the CMS is still loading
* If it looks more difficult than originally thought, take the easier route

**Comment by kldavis4** [comment]
Here's the console.log error that I am seeing:
```
react_devtools_backend.js:3973 Error: Unable to find `TinaProvider`; did you forget to add the TinaCMS container to your app root?  See our setup docs: https://tina.io/docs/introduction/tina-init/#adding-tina
    at Module.f [as useEditState] (vendor.57ae31d1.js:2446:39797)
    at Ute (vendor.57ae31d1.js:4378:344)
    at Ere (vendor.57ae31d1.js:30:53551)
    at p$e (vendor.57ae31d1.js:34:8889)
    at c$e (vendor.57ae31d1.js:34:967)
    at APt (vendor.57ae31d1.js:34:890)
    at YP (vendor.57ae31d1.js:34:739)
    at Yre (vendor.57ae31d1.js:32:10999)
    at vendor.57ae31d1.js:30:39293
    at t.unstable_runWithPriority (vendor.57ae31d1.js:19:3823)
```

**Comment by spbyrne** [comment]
I started out by troubleshooting; this issue is specifically coming from the nav component, which is rendered when fullscreen. It relies on context coming from `TinaProvider`. I'll start by making the nav configurable.

**Comment by spbyrne** [comment]
[Here's a PR to fix the issue.](https://github.com/tinacms/tinacms/pull/2885)
