### ISSUE TITLE
  RouteMapping doc improvements:

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1336]
## Summary

RouteMapping docs live in an early concept doc, and could use some updates:
https://tina.io/docs/tinacms-context/#the-routemappingplugin

### Expected Results

- Can we make it clearer where we are using the values of this function (maybe add a screenshot of the CMS document list)
- Unclear where `cmsCallback` goes, or what file the code snippet is from
- Don't need to dynamically import tinacms
- Simplify some lines in the code snippet
E.g
```diff
- if (["pages"].includes(collection.name)) {
+ if (collection.name == "marketingPage") {
```
^ Note, we want to encourage users to name collections as singular

**Comment by jamespohalloran** [comment]
Also, this ticket is related: https://github.com/tinacms/tinacms.org/issues/1334
Might make sense to tackle both at the same time

**Comment by jeffsee55** [comment]
One of the additional things we'd like to tackle is setting this up at the collection level https://github.com/tinacms/tinacms/discussions/2402#discussioncomment-2046317

```
defineSchema({
 collections: [{
   name: "post",
   label: "Posts",
   path: 'content/posts',
   router: (collection, document) => {
     if(document.data.title === "Hello, World!") {
       return "/"
     }
     return `${collection.name}/document.sys.filename}`
   }
 }]
})
```
