### ISSUE TITLE
Add Tina "Create Button" to blog post list view

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#135]
I would like to be able to create new blog posts for tinacms.org within Tina. It would be nice if there was a "create" button in the blog posts list

**Comment by kendallstrautman** [comment]
Similar to the 'edit this post' link but like a 'create' button?

**Comment by kendallstrautman** [comment]
I think this is solved since the 'create' plugin is on the `Layout`. But feel free to reopen if I misunderstood.
