### ISSUE TITLE
Cannot find feature to clone or fork in app. Re:

### ISSUE THREAD

**Issue by menum724** [tinacms/tinacms.org#1365]

**Comment by jamespohalloran** [comment]
Hi there, can you explain a bit more what you're looking for?

**Comment by menum724** [comment]
I see the edit, I think, by dependebot already, pretty sure, and that's good. Otherwise my original goal was to fork the repository or clone it. Make sense? Thanks.

**Comment by jamespohalloran** [comment]
Sorry, I think I'll need a lot more context on what you're trying to do. Is this in reference to tinacms itself? or the tina.io site repository (This repo)

Also, would you find filling out this template, and providing some screenshots or a loom?

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

### Actual result

What actually happened?

### Environment

#### Tinacms Package Versions


```text

```



#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |         |
| npm     |         |
