### ISSUE TITLE
Broken link in 'Using TinaCMS with Next.js' page

### ISSUE THREAD

**Issue by korompaiistvan** [tinacms/tinacms.org#1377]
hi, first of all, thank you for the project, looks like a great alternative to Netlify CMS

I'm working through setting up a Next.js example, but the link to the final repo is broken.
Specifically the issue is with the link on this line: https://github.com/tinacms/tinacms.org/blob/master/content/blog/using-tinacms-with-nextjs.md?plain=1#L29

Unfortunately, I couldn't easily find a replacement for it. Not an issue right now, as I'm reading through the docs anyways but I would imagine you would want to know about it

**Comment by jamespohalloran** [comment]
Thank you very much for the report! PR opened
