### ISSUE TITLE
Need a way to try Tina on the Now preview deployments

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#223]
When clicking "Edit this site", the GitHub auth flow redirects back to tinacms.org/* instead of:
https://tinacms-site-next-git-branchname.tinacms.now.sh/*

We can't send a custom Github callback because Github returns:
```
https://tinacms.org/github/authorizing?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application....
```

**Comment by kendallstrautman** [comment]
duplicate of #263
