### ISSUE TITLE
Docs: Add Wysiwyg Image docs

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms.org#328]
Need to document the image config options for the Markdown, HTML, & InlineWysiwyg fields.

**Comment by kendallstrautman** [comment]
@DirtyF - are you familiar with this config? Want to take this on?

**Comment by DirtyF** [comment]
What config you're refering to, I've mostly inserted images in the inline wysiwyg fields. Would love to help.

**Comment by kendallstrautman** [comment]
I just saw that you can set `imageProps` on the `Wysiwyg` now — do we have this set on up on any of the demo's? Or how have we been testing the wysiwyg image stuff?

**Comment by DirtyF** [comment]
I did test it on the Gatsby demo. @ncphillips implemented it in https://github.com/tinacms/tinacms/commit/4c9aa82ade62ee4b46e9444592206a6931733d4d

https://github.com/tinacms/tinacms/blob/c2663fa2c089a599d6c031967b972a577d4994fa/packages/demo-gatsby/src/templates/blog-post.js#L169-L182

**Comment by RobertBroersma** [comment]
👋 

I found this place by looking for docs on this. @DirtyF your example was very helpful.

Now I'm trying to do this in Gatsby, with Remark + Gatsby Remark Image, aaand I want to colocate the image with the post in `~/content/posts/example-post`

Getting the image in there was quite trivial, but now I have no idea what to do for the `previewUrl`. The image is processed by Gatsby Image and put in some hashed directories in public: `http://localhost:8000/static/b4ef2df4275006fae8baa0c3bc57d13c/00d43/image.png`

Is there any way to accomplish this?

My best idea so far is to also just upload a copy of the image to `/static/` like in @DirtyF's example and show that one in the preview 🤷‍♂️ 

```js
<InlineWysiwyg
  name="rawMarkdownBody"
  imageProps={{
    async upload(files) {
      const directory = path.dirname(post.fileRelativePath);

      let media = await cms.media.store.persist(
        files.map((file) => ({
          directory,
          file,
        }))
      );

      return media.map((m) => `./${m.filename}`);
    },
    previewUrl(url) {
      return ???;
    },
  }}
>
  <div
    dangerouslySetInnerHTML={{
      __html: data.markdownRemark.html,
    }}
  />
</InlineWysiwyg>
```

**Comment by DirtyF** [comment]
@jpuri will provide a reference implementation for `imageprops`
We should also state what the default value is for the `sticky` option.

**Comment by kendallstrautman** [comment]
Where will this reference live @DirtyF?

**Comment by DirtyF** [comment]
@kendallstrautman I was thinking https://tinacms.org/docs/ui/inline-editing/inline-wysiwyg, where do you think it should live?

**Comment by kendallstrautman** [comment]
Aren't these docs applicable to the inline wysiwyg, markdown & html fields? Whichever field we think is most applicable, let's put it there and then make sure to link to in the other field docs.

**Comment by kendallstrautman** [comment]
Implemented in the [`react-tinacms-editor` README](https://tinacms.org/packages/react-tinacms-editor)
