### ISSUE TITLE
sticky Wysiwyg menu hidden behind Toolbar

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#330]
When in edit-mode:
On the docs (or blog page), if you click into the inline Wysiwyg section, if you scroll down, the Wysiwyg menu gets hidden behind the toolbar

**Comment by kendallstrautman** [comment]
I think we should make an issue for this in `tinacms`

**Comment by kendallstrautman** [comment]
@spbyrne is this still an issue?
