### ISSUE TITLE
Open Authoring - Ability to add new docs pages

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#341]
It would be nice to be able to create/edit new docs pages with Tina open-authoring.
There's currently no create button in the Docs pages. 
I manually created the page in my fork, but the new page 404'ed (I assume because [fallback: false](https://github.com/tinacms/tinacms.org/blob/master/pages/docs/%5B...slug%5D.tsx#L125) on the docs layouts)

**Comment by dwalkr** [comment]
fallback is likely the reason it 404s. For reference, this is what we had to do for the blog routes: https://github.com/tinacms/tinacms.org/pull/276

**Comment by jamespohalloran** [comment]
Closing in favor of https://github.com/tinacms/tinacms.org/issues/1178
