### ISSUE TITLE
Website shows Privacy Error

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [tinacms/tinacms.org#348]
Website shows Privacy Error

Your connection is not private
Attackers might be trying to steal your information from tinacms.org (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID

Help improve Chrome security by sending URLs of some pages you visit, limited system information, and some page content to Google. Privacy policy

**Comment by DirtyF** [comment]
Hey, I can not reproduce this. Are you still experiencing this issue?

**Comment by kendallstrautman** [comment]
@VinayaSathyanarayana could you share more info on your browser user agent?

**Comment by VinayaSathyanarayana** [comment]
Not sure what was the issue... It is working fine now.
