### ISSUE TITLE
Docs: Switch Next docs to use useForm instead of useRemarkForm

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#351]
Our Next docs are designed around using the git on the filesystem backend. They should be reworked to not use a backend, and switch the form to use `useForm`. 
The `onSubmit` function can be something simple like: 
`alert("You clicked save")`

We will want to switch, as the git approach requires much more setup (starting the app with Express) which won't be required for API-based backends (I.e our Github backend)

**Comment by kendallstrautman** [comment]
@dwalkr - the new nextjs guide accomplishes this right?

**Comment by dwalkr** [comment]
Yep the nextjs bootstrapping guide in #374 does exactly this
