### ISSUE TITLE
Docs: Guide on converting from Next git client to Github client 

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#352]
There is a lot of work required to convert a Next implementation from using the Git backend, to the [Github backend](https://github.com/tinacms/tinacms.org/pull/344).

We should have a guide helping them through the process

**Comment by jamespohalloran** [comment]
I wonder if this task is still imperative now that our Github guide has been reworked to show setting it up on a fresh `create-next-app` site. Thoughts @ncphillips @kendallstrautman @dwalkr ?

**Comment by ncphillips** [comment]
Agreed. Probably can be lowered or even dropped from the list entirely

**Comment by jamespohalloran** [comment]
Removing it from the open-authoring v1 project for now

**Comment by kendallstrautman** [comment]
This is stale, closing — We will consider making a guide for this type of migration if folks ask for it
