### ISSUE TITLE
RSS Feed doesn't work properly

### ISSUE THREAD

**Issue by ycrack** [tinacms/tinacms.org#376]
When I access to `tinacms.org/rss.xml`, it returns `500 | Internal Server Error`.
But it deployed at #29 is working properly.

**Comment by kendallstrautman** [comment]
Confirmed the feed is not currently working. I think @logan-anderson wrote a blog or has a good idea on how to fix this. Care to share Logan?

**Comment by logan-anderson** [comment]
> Confirmed the feed is not currently working. I think @logan-anderson wrote a blog or has a good idea on how to fix this. Care to share Logan?
@kendallstrautman 
Yeah I added one to my blog and I also [posted about it](https://logana.dev/blog/rss-feeds-in-a-nextjs-site)

**Comment by dwalkr** [comment]
https://github.com/tinacms/tinacms.org/pull/657
