### ISSUE TITLE
Github Authorization dialog gets stuck if GitHub OAuth window is closed without authorizing

### ISSUE THREAD

**Issue by IronSean** [tinacms/tinacms.org#380]
To reproduce:

1. Click **Edit This Page**
2. Click **Continue to GitHub**
3. Close GitHub authentication window. 

The TinaCMS.org page is now stuck in this state until you refresh:
![image](https://user-images.githubusercontent.com/1960190/80329440-b70e9400-8818-11ea-8534-98dca9a6f23e.png)

**Comment by ncphillips** [comment]
👍 thanks!

May get fixed by https://github.com/tinacms/tinacms/pull/1057

**Comment by DirtyF** [comment]
This looks fixed to me.
