### ISSUE TITLE
create-react-app guides

### ISSUE THREAD

**Issue by saihaj** [tinacms/tinacms.org#438]
Hey, are there any guides I can follow for a create-react-app ?

**Comment by dwalkr** [comment]
Hi @saihaj - 

Currently we don't have guides for create-react-app. I'm currently working on a GitHub API flow that can be used with a create-react-app site, and we'll be publishing a guide on that in the coming weeks!

I'll leave this issue open and come back with an update when we post the guide.

**Comment by saihaj** [comment]
GitHub actions will be used for builds ? Right?

**Comment by kendallstrautman** [comment]
We created an [intro tutorial](https://tinacms.org/docs/getting-started/introduction) with CRA! Feel free to post additional questions or ideas on [the forum](munity.tinacms.org/) for a CRA guide
