### ISSUE TITLE
Open Authoring Guide results in blank form

### ISSUE THREAD

**Issue by chuanqisun** [tinacms/tinacms.org#447]
I wonder if I missed something. I followed the guide line by line till the end of [Loading Content from Github](https://tinacms.org/guides/nextjs/github-open-authoring/loading-github-content) and yet I am getting blank form after clicking the pencil button.

After comparing the code with the [Gatsby Guide](https://tinacms.org/guides/gatsby/adding-tina/creating-forms), I found that the Next.js Open Authoring Guide is missing this step
```diff
  const [post, form] = useForm(formConfig)
+ usePlugin(form)
```

Please check the doc. I apologize if I missed something obvious. Otherwise, please fix the doc. Thanks!

**Comment by ncphillips** [comment]
You are totally right! Thank you 😄
