### ISSUE TITLE
Individual field options are inconsistent in docs

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#459]
In the [blocks](https://tinacms.org/docs/fields/blocks#blocks-field-options) field options, it lists some but not all of the base field options (`format` & `parse` are missing). It confused me at first why 'component' should be an option here, as in the case of blocks it should always just be 'block'.

The[ number field options](https://tinacms.org/docs/fields/number#options) states that the component value should always just be 'number' in the case of the number field which clarifies this a bit. 
The options `NumberConfig ` example also extends FieldConfig, but redefines the following properties:
```
  component: 'number'
  name: string
  label?: string
  description?: string
```

It also gives the following blurb that is missing in some other field pages:
```
This interfaces only shows the keys unique to the number field.

Visit the Field Config docs for a complete list of options.
```

**Comment by ncphillips** [comment]
Yeah I started updating them last week. Didn't finish all the fields. All of the fields will eventually be like those of the Number field
