### ISSUE TITLE
Fix Open Authoring Setup

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms.org#472]
**Issue**
Given I am reviewing a PR
When I preview https://tinacms-site-next-git-editable-guides.tinacms.now.sh/
Then I can edit and see Tina's UI.

**Demo**
https://www.loom.com/share/9baa09a92be540b98a610584990a44fd

Based on the conversation in the TinaCMS chat, it's a configuration issue with GitHub OAuth.

**Comment by kendallstrautman** [comment]
Is this still an issue @DirtyF?

**Comment by DirtyF** [comment]
It looks fixed now, thanks for the reminder @kendallstrautman
