### ISSUE TITLE
Docs: Document content creation generically and/or with Next.js

### ISSUE THREAD

**Issue by IronSean** [tinacms/tinacms.org#488]
Currently there is documentation and helper plugins for Gatsby to help facilitate creating new content using TinaCMS. However there is no equivalent for Next.js, or in the generic documentation for TinaCMS as a whole.

Next.js sections of the docs do not provide any guidance for doing content creation in the docs pages, in the general TinaCMS from what I can see, or in any of the linked blog posts. There are Gatsby specific blogs and docs, and `gatsby-tinacms-json`/`gatsby-tinacms-remark` contain the content creator helpers   

This repo itself does have an implementation which can be referenced. It uses a specialized BlogPostCreator here:
https://github.com/tinacms/tinacms.org/blob/eeab69fefe371f30c3a284483b485b38507d8ada/tinacms/BlogPostCreator.ts

Which is built upon a more generic MarkdownCreatorPlugin here:
https://github.com/tinacms/tinacms.org/blob/eeab69fefe371f30c3a284483b485b38507d8ada/utils/plugins/MarkdownCreatorPlugin.ts

Which ultimately references the main tinacms package `AddContentPlugin` interface.

However, even that implementation states [here](https://github.com/tinacms/tinacms.org/blob/eeab69fefe371f30c3a284483b485b38507d8ada/utils/plugins/MarkdownCreatorPlugin.ts#L29) that the implementation is `@deprecated in favour of calling `CreateMarkdownPlugin` class directly.`, although that class is not referenced anywhere else in the docs or in the main TinaCMS repo when searched. Does it refer to the `MarkdownCreatorPlugin` class below it?

For a generic approach, does this look correct?

1. Create a Content Creator by  implementing the `AddContentPlugin` interface from the main tinacms package, which will handle the defaults of the format and location of your stored content.
2. Add the plugin to components with `usePlugin` and an "add ${content}" button will appear on the site.

**Comment by kendallstrautman** [comment]
See this new doc on [content creators](https://tinacms.org/docs/plugins/content-creators)
