### ISSUE TITLE
open authoring seems to be broken

### ISSUE THREAD

**Issue by sakulstra** [tinacms/tinacms.org#512]
getting 
![image](https://user-images.githubusercontent.com/4396533/86259101-e5637380-bbbb-11ea-95fd-4ee9052aeb62.png)
when trying to create a fork

wanted to fix: https://tinacms.org/blog/2020-06-29-release-notes as:
```
      onClick={
-       github.editMode ? github.exitEditMode : github.enterEditMode
+       cms.enabled ? cms.disable() : cms.enable()
      }
```

should probably be:
```
      onClick={
-       github.editMode ? github.exitEditMode : github.enterEditMode
+       cms.enabled ? cms.disable : cms.enable
      }
```

**Comment by DirtyF** [comment]
Is your fork named `origin`, I believe it's a current limitation at the moment.

**Comment by DirtyF** [comment]
Works for me, I just opened a PR through the site.

**Comment by sakulstra** [comment]
hmm it seems to work - but really unreliable, created the pr #514, but after a reload i again got this similarly weird error

![image](https://user-images.githubusercontent.com/4396533/86270209-27e07c80-bbcb-11ea-993e-8d65f1b297b4.png)

pressing continue doesn't do anything. Reloading brouhgt me to the page requesting me to fork again - although i already have a fork.

**Comment by kendallstrautman** [comment]
@sakulstra, we just updated everything to the latest versions of Tina packages, could you let us know if this is still an issue?

**Comment by sakulstra** [comment]
I think it work now 👍
