### ISSUE TITLE
"Creating new files" docs section only available in Gatsby nav

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#547]
I was looking to add the createRemarkButton to my Next site so I checked the docs. If I'm not mistaken, the only docs around creating new files is in the Gatsby section. 

Our tinacms.org site uses: `import { createRemarkButton } from 'gatsby-tinacms-remark'`. Should we move that out to a more general package?

**Comment by kendallstrautman** [comment]
[See this doc](https://tinacms.org/docs/plugins/content-creators)
