### ISSUE TITLE
All pages must pass `preview` state thru `getStaticProps` for edit mode to work correctly

### ISSUE THREAD

**Issue by dwalkr** [tinacms/tinacms.org#601]
While setting up a test page I noticed that the edit mode toggle doesn't work right on certain pages. The cms is initialized as enabled/disabled depending on whether `preview` is passed in the page's inital props. This can cause problems trying to enter/exit edit mode on pages that aren't passing that var.

We can either make sure all pages pass the `preview` var or fix the initialization to handle cases where `preview` does not exist in `pageProps`

**Comment by dwalkr** [comment]
https://github.com/tinacms/tinacms/pull/1362

**Comment by ncphillips** [comment]
Fixed
