### ISSUE TITLE
502 Error when editing site and navigating to Guides

### ISSUE THREAD

**Issue by laurenclark** [tinacms/tinacms.org#605]
`Error 502 Ray ID: 5bb1874f2e82ce1f • 2020-07-30 19:36:27 UTC`
Works fine for the rest of the site and docs but Cloudflare gives me a 500 error when I hit Guides.

**Comment by dwalkr** [comment]
We pushed a fix for this yesterday. Can you let me know if you're still having this problem?

**Comment by laurenclark** [comment]
Yes working now! I've tested all the other routes, everything working as expected.

**Comment by DirtyF** [comment]
Thanks for the feedback @laurenclark 😊
