### ISSUE TITLE
Cool URIs don't change

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms.org#620]
Given I search tinacms releases in a search engine 
<img width="617" alt="Capture d’écran 2020-08-04 à 23 50 24" src="https://user-images.githubusercontent.com/103008/89348783-6f1bca80-d6ad-11ea-95a1-d98816e2bd7e.png">
When I click on https://tinacms.org/blog/2020-06-29-release-notes
Then I get a 404

Suggestion: 301 redirect to https://tinacms.org/docs/releases/2020-06-29  
Bonus points: Canonical URL

**Comment by ncphillips** [comment]
weird I thought I got that
