### ISSUE TITLE
Make docs code blocks copy & paste better

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms.org#622]
Is it possible to improve copy+paste on the code blocks?

Right now the + signs come along with the copy paste. Ideally, they would be excluded, in that highlighting/clicking the block or a button in the block just copies the correct source code to your clipboard.

_Originally posted by @chrisdmacrae in https://github.com/tinacms/tinacms.org/pull/590#issuecomment-668801772_

**Comment by chrisdmacrae** [comment]
cc @kendallstrautman @ncphillips

**Comment by kendallstrautman** [comment]
Implemented via #631
