### ISSUE TITLE
502 error when editing on an old branch

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms.org#669]
Given I'm editing https://tinacms.org on the `testing-1` branch
When I open https://tinacms.org/docs/apis
Then I get a 502 error

<img width="998" alt="Capture d’écran 2020-08-14 à 11 42 49" src="https://user-images.githubusercontent.com/103008/90237027-e7a82700-de23-11ea-962a-ce88a986ad71.png">

**Comment by dwalkr** [comment]
confirmed fixed by https://github.com/tinacms/tinacms.org/pull/672
