### ISSUE TITLE
Using Group Fields to organize flat front matter

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms.org#74]
I setup Tina on my blog and made this form:

```js
const BlogPostForm = {
  label: "Post",
  fields: [
    {
      name: "rawFrontmatter.title",
      component: "text",
      label: "Title",
      required: true,
    },
    {
      name: "description",
      component: "textarea",
      label: "Description",
    },
    {
      name: "date",
      component: "date",
      label: "Last Updated",
    },
    {
      name: "publishDate",
      component: "date",
      label: "Published",
    },

    { name: "rawMarkdownBody", component: "markdown", label: "Body" },
  ],
}

export default remarkForm(BlogPostTemplate, BlogPostForm)
```

I didn't love the organization in the sidebar though. I rarely care about the descriptions or dates when editing my content. It really lengthens out the form:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/824015/66135949-15e89380-e5d1-11e9-95a0-afd2006786b1.png">

I used the `group` field shove those hide those extra fields. Now the form template looks like this:

```js
const BlogPostForm = {
  label: "Post",
  fields: [
    {
      name: "rawFrontmatter",
      label: "Metadata",
      component: "group",
      fields: [
        {
          name: "date",
          component: "date",
          label: "Last Updated",
        },
        {
          name: "publishDate",
          component: "date",
          label: "Published",
        },
        {
          name: "description",
          component: "textarea",
          label: "Description",
        },
      ]
    },
    {
      name: "rawFrontmatter.title",
      component: "text",
      label: "Title",
      required: true,
    },

    { name: "rawMarkdownBody", component: "markdown", label: "Body" },
  ],
}
```

And my sidebar looks like this:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/824015/66136245-88597380-e5d1-11e9-8b9c-743fb8a2998d.png">

<img width="341" alt="image" src="https://user-images.githubusercontent.com/824015/66136264-8ee7eb00-e5d1-11e9-93f5-0bd811211155.png">

**Comment by jamespohalloran** [comment]
Closing in favor of https://github.com/tinacms/tinacms.org/issues/1178
