### ISSUE TITLE
Warn people about global styles with `styled-components`

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms.org#75]
The component created by `createGlobalStyles` function in `styled-components` is extremely inefficient. This will cause sites being edited with TinaCMS to eventually start to crawl.

Any global styles should be memoized:

```jsx
const GlobalStyle = createGlobalStyle`
  html {
    min-height: 100%;
  }
`
export default React.memo(() => <GlobalStyles />);
```

We should have a guide/blog post about this.

**Comment by jamespohalloran** [comment]
Closing, as we are internally moving from styled-components to tailwind
