### ISSUE TITLE
Forking repository failed on Safari 14

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms.org#754]
**What happens?**

Getting an error message when asked to fork the repo:

```A fork of this website is required to save changes.
Forking repository failed. Are you sure the repository is public?
```

- The repo is public
- My fork is even with current `master` branch
- Revoking the GitHub app doe not fix the issue
- Deleting Cookies does not fix the issue

The message is misleading, looks like an auth issue. 🤔 

**Expected**

```gherkin
Given I'm connected on GitHub and I browse tina's website on tina.io
When I click on the Edit button 
Then I can edit content.
```

**Comment by kendallstrautman** [comment]
Did you try clearing cookies?

**Comment by DirtyF** [comment]
I just did, I still get `Forking repository failed. Are you sure the repository is public?`

**Comment by kendallstrautman** [comment]
Oh I see, Safari............. 😩

**Comment by DirtyF** [comment]
[Safari is currently 19% of the browser market share](https://gs.statcounter.com/browser-market-share)

**Comment by jamespohalloran** [comment]
Closing in favor of https://github.com/tinacms/tinacms.org/issues/1178
