### ISSUE TITLE
Update Docs for tinacms#520

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms.org#77]
A [pull request](https://github.com/tinacms/tinacms/pull/520) in tinacms may require documentation updates.

The following files may need to be updated:

| File | Reason |
| --- | --- |
| [creating-forms.md](https://github.com/tinacms/tinacms-site/tree/master//content/docs/nextjs/creating-forms.md) | Demonstrates using useLocalForm on a Next.js site |,| [using-tinacms-with-nextjs.md](https://github.com/tinacms/tinacms-site/tree/master//content/blog/using-tinacms-with-nextjs.md) | Demonstrates using useLocalForm on a Next.js site |

## Probable Change

We may want to add a Tip on how to prevent forms from being registered in production

**Comment by kendallstrautman** [comment]
This is stale, closing
