### ISSUE TITLE
where are docs content stored?

### ISSUE THREAD

**Issue by KnowsCount** [tinacms/tinacms.org#771]
I started trying Tina out recently and I think it's great.. Now as a Chinese speaker, I would love to translate Tina docs into Chinese as internationalisation is certainly important; yet I cannot find where the docs are stored and can ergo not change it in forks and open a pull request and everything in future.. 

Can anyone help me with that?– or I can try figure it out by reading the code. I do not reckon I will have all those time recently though.

**Comment by DirtyF** [comment]
Hi, we do have an [i18n plugin to help with translating content](https://github.com/tinalabs/react-tinacms-i18n).
We do not intend to maintain i18n docs until tinamcs reached 1.0, but feel free to fork the site and start translating for the Chinese community.

**Comment by KnowsCount** [comment]
I see. The fact that tinacms is not yet in its version 1.0, it is already so good is quite appalling. 
So... I would love to start translating in my spare time. Thanks!
