### ISSUE TITLE
Image on the community page is broken

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#794]
Image on the community page is broken: https://tina.io/community/

<img width="1112" alt="Screen Shot 2021-02-10 at 11 29 23 AM" src="https://user-images.githubusercontent.com/3323181/107531524-4c55fb80-6b93-11eb-8b69-7cccc01d4539.png">

**Comment by DirtyF** [comment]
hum, It's working locally 🤔
