### ISSUE TITLE
Tina Cloud docs integration

### ISSUE THREAD

**Issue by ashleyjanedoiron** [tinacms/tinacms.org#802]
- [ ] Create a redirect from tina.io/cloud-docs to our Vercel deployment

**Comment by ashleyjanedoiron** [comment]
- [ ] Improve Tina Cloud's overview section
- [ ] Why Tina Cloud section
- [ ] Setup Tina Cloud Client section can be simplified
- [ ] Work with @jeffsee55 to go through Reference pages for out of date content
- [ ] Fix broken links/TOC content

**Comment by DirtyF** [comment]
https://tina.io/docs/ has been updated since, is there any left missing there?

**Comment by perkinsjr** [comment]
Closing this issue, it's old and we have addressed a lot of these with all our changes.
