### ISSUE TITLE
Teams - Need docs around `tina serve` command

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#83]
Could use some examples and extended docs around `tina serve` options:
https://github.com/tinacms/tinacms-site/blob/teams-docs/content/docs/teams/cli/commands.md#tina-serve-options--tina-server-options

**Comment by DirtyF** [comment]
`tina serve` is no more an option at the moment IIRC

**Comment by kendallstrautman** [comment]
This is stale, closing
