### ISSUE TITLE
Guide Title Context and Navigation

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms.org#879]
To improve context when reading a guide, and make better use of the sidebar hierarchy, I'd like to introduce the guide title as a level in the sidebar and push the guide steps down a level. Currently when you're on a guide, the name isn't displayed anywhere and the guide steps appear as a top level link in the sidebar. 

Current:

<img width="476" alt="Screen Shot 2021-05-27 at 4 10 29 PM" src="https://user-images.githubusercontent.com/5075484/119883593-14868000-bf06-11eb-84d6-96c1517f8279.png">

Revised:

<img width="499" alt="Screen Shot 2021-05-27 at 4 11 11 PM" src="https://user-images.githubusercontent.com/5075484/119883662-2a944080-bf06-11eb-9756-662c18500cbe.png">

This can be done without changing the nav component, but there's something very 'wrong' about the way my solution looks and I'd like input.

Existing code (lines 235-243 of `[step].tsx`:
```
        {
          title: guide.title,
          id: guide.title,
          collapsible: false,
          items: guide.steps,
          returnLink: {
            url: '/guides',
            label: '‹ Back to Guides',
          },
        },
```

Code used to show revised nav:
```
        {
          title: guide.title,
          id: guide.title,
          collapsible: false,
          items: [
            {
              title: guide.title,
              id: guide.title + 2,
              collapsible: false,
              items: guide.steps,
            },
          ],
          returnLink: {
            url: '/guides',
            label: '‹ Back to Guides',
          },
        },
```

An alternate solution is to leave the nav as-is and introduce the guide title as a breadcrumb above the current step title in the main document view.

**Comment by jamespohalloran** [comment]
I was poking around the guides and got a bit lost. I think this would help a lot.
