### ISSUE TITLE
iframe is being stripped of allowfullscreen 

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms.org#894]
When posting an iframe for Youtube videos, none of our videos are allowed to be in fullscreen. 

Looking futher into the issue the markdown had the correct information for example:

<iframe width="560" height="315" src="https://www.youtube.com/embed/Y-fG7qzoHKw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

However when displayed on the page the allowfullscreen is removed which disabled fullscreen.

<iframe width="558" height="313" src="https://www.youtube.com/embed/Y-fG7qzoHKw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"></iframe>

Here is an example post https://tina.io/blog/announcement-tina-cloud-is-officially-in-alpha/

**Comment by DirtyF** [comment]
Maybe with `allowfullscreen="true"`?

**Comment by perkinsjr** [comment]
Yeah it's a bit of a strange problem, It's probably a parsing rule. The allowfullscreen=true does fix the issue so I will deploy that.
