### ISSUE TITLE
UX: youTube video breaks layout on mobile

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms.org#898]
[On the alpha blog post](https://tina.io/blog/announcement-tina-cloud-is-officially-in-alpha/), the full with of the video makes the content narrower on mobile. 😞 

This is a common issue with many workarounds
Chris Coyier published a [Vanilla JS solution to automate this](https://codepen.io/chriscoyier/pen/YzXeXjK) and allow users to copy-paste youTube embeds to avoid having to add a wrapper around the iframe.

Reported by our beloved @kendallstrautman ❤️ 

/cc @spbyrne

**Comment by spbyrne** [comment]
If we want to assume all inline videos are 16:9 (usually a safe assumption) we can do this with CSS. Even in the event they're a bit of an odd aspect ratios black bars are better than a broken layout.

**Comment by spbyrne** [comment]
Ah, I see what you're saying about the lack of a wrapper; your linked example code uses the exact CSS I was going to use but of course automatically adds the wrapper automatically and even adjusts the aspect ratio on the fly. I'm sold, I'll see about using something like that instead.

**Comment by spbyrne** [comment]
I got the video code working but it's not what's breaking the mobile layout for the most part. I had a fix for that in the design updates branch (footer changes) so I'll create a PR for this video fix but the mobile improvements will come with that design refresh PR.
