### ISSUE TITLE
Add analytics for docs section

### ISSUE THREAD

**Issue by ashleyjanedoiron** [tinacms/tinacms.org#926]

**Comment by DirtyF** [comment]
We currently don't have the details of the pages visited on Google Analytics, it would be nice to make sure we fix this in order to see what pages and sections are the most visited.

> 
> The Landing Pages report has a (not set) entry.
> 
> A pageview hit must precede event hits in order for the event hits to include the page that they fire from. When event hits aren't preceded by a pageview, Google Analytics doesn't have the page for the event hits, so their page is (not set).
> 
> Verify that tracking code for property Tina sends a pageview hit before sending any events.
>

**Comment by perkinsjr** [comment]
Confirmed that GA is working in the docs.
