### ISSUE TITLE
Tina Cloud getting started guide and CLI

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms.org#959]
@perkinsjr , Should we ask readers to install the tina CLI (or reference the CLI docs) before we ask them to run `npx @tinacms/cli init` [here](https://tina.io/guides/tina-cloud/getting-started/create-app/#adding-tina)?

**Comment by perkinsjr** [comment]
@scottgallant  We don't need people to install the CLI as npx will  temporary install and invoke the package for the user,  but we will be referencing the docs once the init section is finished today.
