### ISSUE TITLE
docs: confused by the content of the guide to add tinamms to Next.js blog starter

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms.org#965]
Given I'm following https://tina.io/guides/tina-cloud/getting-started/create-app/
When I edit http://localhost:3000/demo/blog/HelloWorld
Then  I don't see a "smaller guide", and WYSIWYG is not active as described on the page
And the GIF is not reflecting what I see

User Testing Session: https://www.loom.com/share/06d4cdaa7fe146f3bb0d4ea069d51aa6

**Comment by logan-anderson** [comment]
@DirtyF @perkinsjr the guide dropped in the CLI is going to be removed for clarity.
