### ISSUE TITLE
graphql docs uses different schema than starter

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#977]
I noticed that there's a few discrepancies vs what's used in the starter, vs what's in our [graphql docs](https://tina.io/docs/graphql/) (e.g getPostList vs getPostsList)

We also say:

> Note: The following schema is used in all examples

**Comment by spbyrne** [comment]
I'm assuming "The following schema is used in all examples" refers to the examples on that page.

**Comment by jamespohalloran** [comment]
Closing in favor of https://github.com/tinacms/tinacms.org/issues/994
