### ISSUE TITLE
Not always obvious graphql docs are dependant on schema

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#978]
On the [graphql](https://tina.io/docs/graphql/) page of our docs, I'm not sure it's super clear that the fields are dependent on the user's schema. 

Also, I know we have a blurb at the top, but if you navigate directly to a query in the sidebar, that can easily be missed
<img width="1288" alt="Screen Shot 2021-08-02 at 1 10 32 PM" src="https://user-images.githubusercontent.com/3323181/127891731-c06669a4-b70b-495c-be24-53a0599a2f9c.png">

I'm wondering if the header names (and sidebar nav) should reference things like `update{name}Document` rather than `updatePostDocument`

**Comment by spbyrne** [comment]
I could see the headings using `update{name}Document` for clarity with a small sentence below to explain in this example we'll use the post collection from the schema at the top of the page, that way the ToC is more clear and in isolation you're always referencing back to the schema at the top of the page.

**Comment by spbyrne** [comment]
It took a while for it to click for me that "getPostList" is not an innate part of the API but a reference to something you've defined as a 'post' collection, despite the fact I knew how things were defined/referenced/generated.
