### ISSUE TITLE
chore: Fix all warnings in the site

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms.org#99]
For example: 

- `Warning: Each child in a list should have a unique "key" prop.`
- `Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?`

Let's cleanup up all these little issues.

**Comment by danditomaso** [comment]
I'd be happy to take this on.

**Comment by kendallstrautman** [comment]
That'd be awesome! Thank you 🤗

**Comment by danditomaso** [comment]
Sorry about the delay in getting this done. Being housebound for a few weeks has left me with a lot of spare time. I took a look at the project today and found a few small-ish issues that weren't listed above and fixed them. I'm not able to locate the missing key errors you mentioned above. Do you know which specific page has been generating this error?

**Comment by DirtyF** [comment]
@danditomaso we fixed some key warnings since in #182

**Comment by kendallstrautman** [comment]
This is mostly a Tina issue, closing
