### ISSUE TITLE
Inconsistent pluralization on get{Collection}Document

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#994]
We have some examples in our docs that use queries like `getPostDocument`https://tina.io/docs/graphql/

Other docs refer to `getPostsDocument` https://tina.io/guides/tina-cloud/add-tinacms-to-existing-site/next-changes/

I understand this is because the schema can define a collection name as "post" vs "posts", but we should keep it consistent ("post" makes the most sense to me).

We will also need to update this in a few places outside the docs such as:
- Our readme's in the tinacms repo
- Our starter(s)
- The CLI auto-code-gen

**Comment by mitchmac** [comment]
@jamespohalloran - do you have a preference for the naming pattern. Seems like consensus on OSS team prefers singular.

**Comment by jamespohalloran** [comment]
Yeah I'd definitely lean singular, otherwise `getPostsDocument` vs `getPostsList` is less clear

**Comment by jeffsee55** [comment]
Yeah I agree singular is better, we initially did plural. And just to add a little bit of context. I originally just wanted it to be `post` or `getPost`, etc. But _if_ you used a plural name, `posts` or `getPosts` is obviously really unclear, so adding the `Document` and `List` suffixes was a way to make that explicit. We _could_ enforce singular naming and pull in some libraries to helps us validate it, but not sure it matters much.
